export const SET_USER = 'SET_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'
export const REMOVE_LOADING = 'REMOVE_LOADING'
export const SET_SESSIONS = 'SET_SESSIONS'
